apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activemq
  template:
    metadata:
      labels:
        app: activemq
    spec:
      containers:
      - name: activemq
        image: rmohr/activemq
        ports:
        - containerPort: 61616
        - containerPort: 8161
---
apiVersion: v1
kind: Service
metadata:
  name: activemq
spec:
  ports:
    - port: 61616
      targetPort: 61616
    - port: 8161
      targetPort: 8161
  selector:
    app: activemq