apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activemq
  template:
    metadata:
      labels:
        app: activemq
    spec:
      containers:
      - name: activemq
        image: rmohr/activemq
        ports:
        - containerPort: 61616
        - containerPort: 8161
---
apiVersion: v1
kind: Service
metadata:
  name: activemq
spec:
  type: NodePort
  ports:
    - name: amq
      port: 61616
      targetPort: 61616
    - name: web
      port: 8161
      targetPort: 8161
      nodePort: 30001
  selector:
    app: activemq
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: activemq-ingress
spec:
  rules:
  - host: activemq.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: activemq
            port:
              number: 8161
